server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: cambio-service/v3/api-docs
  swagger-ui:
    config-url: /cambio-service/v3/api-docs/swagger-config
    url: /cambio-service/v3/api-docs
spring:
  application:
    name: cambio-service
  sleuth:
    sampler:
      probability: 1.0 #em dev 100% traces
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    username: lucas2
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/cambio-service?useTimezone=true&serverTimezone=UTC
    user: lucas2
    password: admin
  zipkin:
    base-url: http://localhost:9411/
    