version: '3.4'
services:
  naming-server:
    image: lucasemanoel/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - spring-network
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge
