server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LucasEmanoel/spring-config-server
          default-label: main
          #username: LucasEmanoel
          #password: 43121241
          search-paths:
          - 'greeting-service*'
          
