name: Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Log in Docker Hub
        uses: actions/checkout@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

 
